### PR TITLE
Add ByteBuffer Constructor

### PR DESCRIPTION
**Pull request by efaurie**
I think adding a straight ByteBuffer constructor makes some scenarios easier. If the source file is compressed, requiring a byte array means decompressing the entire file into memory first.

### CODE REVIEW

**Comment by GreyCat** [comment]
Sure, why not :)
I don't think that this will help a lot with working on compressed data. You still need to either a pretty sophisticated indexed compression scheme, or decompress all data to be able to seek to arbitrary byte #n in decompressed stream.

**Comment by gmacon** [comment]
Do we have any idea when to expect a new release to Maven Central that contains this update?

**Comment by GreyCat** [comment]
Generally, we release runtimes together with new version of compiler. If you're ok with using `-SNAPSHOT` version, I can publish it right away, though.

**Comment by gmacon** [comment]
We have a "no SNAPSHOT" policy; don't worry about it. Thanks for letting me know.

**Pull request merged**
